#!/bin/bash

# Первоначальная настройка SSL с Let's Encrypt
# Только получает сертификат и записывает nginx конфиг
# После этого запустите: ./auto-deploy.sh

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

COMPOSE_FILE="docker-compose.prod.yml"

# --- Загрузка .env ---

if [ ! -f .env ]; then
    echo -e "${RED}❌ Файл .env не найден!${NC}"
    echo ""
    echo "  cp .env.example .env"
    echo "  nano .env"
    exit 1
fi

export $(grep -v '^#' .env | xargs)

if [ -z "$DOMAIN" ] || [ -z "$SSL_EMAIL" ]; then
    echo -e "${RED}❌ DOMAIN или SSL_EMAIL не указаны в .env${NC}"
    exit 1
fi

echo "🔐 Let's Encrypt SSL Setup"
echo "=========================="
echo "Domain: $DOMAIN"
echo "Email:  $SSL_EMAIL"
echo ""

# --- 1. Временный nginx конфиг (только для ACME challenge) ---

echo -e "${YELLOW}📝 Creating temporary nginx config...${NC}"
cat > nginx/conf.d/default.conf << EOF
server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 503;
    }
}
EOF

# --- 2. Запуск nginx для ACME challenge ---

echo -e "${YELLOW}🚀 Starting nginx...${NC}"
docker-compose -f $COMPOSE_FILE up -d --no-deps nginx
sleep 3

# --- 3. Получение сертификата ---

echo -e "${YELLOW}🔐 Requesting SSL certificate...${NC}"

if docker-compose -f $COMPOSE_FILE run --rm --entrypoint certbot certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    --email $SSL_EMAIL \
    --agree-tos \
    --no-eff-email \
    -d $DOMAIN; then
    echo -e "${GREEN}✓ Certificate obtained${NC}"
else
    echo -e "${RED}✗ Failed to obtain certificate!${NC}"
    echo "  - Домен направлен на этот сервер?"
    echo "  - Порт 80 открыт?"
    docker-compose -f $COMPOSE_FILE stop nginx 2>/dev/null || true
    exit 1
fi

# --- 4. Проверка сертификата ---

echo -e "${YELLOW}🔍 Verifying certificate...${NC}"
CERT_INFO=$(docker-compose -f $COMPOSE_FILE run --rm --entrypoint certbot certbot certificates 2>/dev/null | grep -A 5 "$DOMAIN" | head -6)

if ! echo "$CERT_INFO" | grep -q "$DOMAIN"; then
    echo -e "${RED}✗ Certificate verification failed!${NC}"
    docker-compose -f $COMPOSE_FILE run --rm --entrypoint certbot certbot certificates 2>&1 | head -20
    docker-compose -f $COMPOSE_FILE stop nginx 2>/dev/null || true
    exit 1
fi

echo -e "${GREEN}✓ Certificate verified${NC}"
echo "$CERT_INFO" | grep -E "Certificate Name|Domains|Expiry" || true

# --- 5. Записать полный nginx конфиг с SSL ---

echo -e "${YELLOW}📝 Writing SSL nginx config...${NC}"
cat > nginx/conf.d/default.conf << EOF
# Auto-generated by init-letsencrypt.sh
# Domain: ${DOMAIN}

# Upstream Django
upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; font-src 'self'; img-src 'self' data: https:; connect-src 'self';" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    client_body_buffer_size 128k;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        limit_req zone=media burst=50 nodelay;
        limit_req_status 429;
        alias /app/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /api/ {
        limit_req zone=api burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://django;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_redirect off;
    }

    location ~ ^/(accounts|api/auth)/ {
        limit_req zone=auth burst=3 nodelay;
        limit_req_status 429;
        proxy_pass http://django;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_redirect off;
    }

    location / {
        limit_req zone=general burst=50 nodelay;
        limit_req_status 429;
        proxy_pass http://django;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

# --- 6. Остановить всё ---

echo -e "${YELLOW}🛑 Stopping containers...${NC}"
docker-compose -f $COMPOSE_FILE down

# --- Готово ---

echo ""
echo -e "${GREEN}✅ SSL setup completed!${NC}"
echo ""
echo "Certificate: /etc/letsencrypt/live/${DOMAIN}/"
echo ""
echo "Следующий шаг:"
echo "  ./auto-deploy.sh"
echo ""
