# Generated by Django 5.1.15 on 2026-02-08 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elephants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Имя получателя')),
                ('message', models.TextField(blank=True, help_text='Персональное сообщение для получателя', verbose_name='Сообщение')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Принят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to=settings.AUTH_USER_MODEL, verbose_name='Принят пользователем')),
                ('elephant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_link', to='elephants.elephant', verbose_name='Слон')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Подарочная ссылка',
                'verbose_name_plural': 'Подарочные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
