# Generated by Django 5.1.15 on 2026-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlink',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Отображаемое имя отправителя (по умолчанию username)', max_length=100, verbose_name='Имя отправителя'),
        ),
    ]
