# Generated by Django 5.1.15 on 2026-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_color',
            field=models.CharField(blank=True, help_text='Только для advanced тарифа, формат: #RRGGBB или HUE:XXX', max_length=10, null=True, verbose_name='Желаемый цвет (HEX) или оттенок'),
        ),
    ]
