# Generated by Django 5.1.15 on 2026-02-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_seed_tariffs'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='payments_or_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='payments_or_user_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='payments_or_created_idx',
        ),
    ]
