# Generated by Django 5.1.15 on 2026-02-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elephant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(help_text='Уникальный цвет в формате #RRGGBB', max_length=7, unique=True, verbose_name='Цвет (HEX)')),
                ('color_r', models.PositiveSmallIntegerField(verbose_name='Красный (R)')),
                ('color_g', models.PositiveSmallIntegerField(verbose_name='Зелёный (G)')),
                ('color_b', models.PositiveSmallIntegerField(verbose_name='Синий (B)')),
                ('image', models.ImageField(upload_to='elephants/%Y/%m/', verbose_name='Изображение')),
                ('is_gifted', models.BooleanField(default=False, verbose_name='Подарен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Заказ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elephants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Слон',
                'verbose_name_plural': 'Слоны',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('color_hex',), name='unique_elephant_color')],
            },
        ),
    ]
