# Generated by Django 5.1.15 on 2026-02-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elephant',
            name='elephants_e_owner_idx',
        ),
        migrations.RemoveIndex(
            model_name='elephant',
            name='elephants_e_created_idx',
        ),
    ]
